name: GitHub Actions Mirror

on: [ push, delete, create ]

jobs:
#  gitlab:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@v1
#
#      - name: 'Mirror to gitlab'
#        uses: pixta-dev/repository-mirroring-action@v1
#        with:
#          target_repo_url:
#            git@gitlab.com:chiupam/surge.git
#          ssh_private_key:
#            ${{ secrets.GITLAB_KEY }}
#
#      - name: Delete Workflow Runs # 删除执行日志
#        uses: Mattraks/delete-workflow-runs@main
#        with:
#          token: ${{ github.token }}
#          repository: ${{ github.repository }}
#          retain_days: 0
#          keep_minimum_runs: 0
#
#  gitee:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@v1
#      - name: 'Mirror to gitee'
#        uses: pixta-dev/repository-mirroring-action@v1
#        with:
#          target_repo_url:
#            git@gitee.com:chiupam/surge.git
#          ssh_private_key:
#            ${{ secrets.GITEE_KEY }}
#
#      - name: Delete Workflow Runs # 删除执行日志
#        uses: Mattraks/delete-workflow-runs@main
#        with:
#          token: ${{ github.token }}
#          repository: ${{ github.repository }}
#          retain_days: 0
#          keep_minimum_runs: 0

  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/chiupam'
          dst: 'gitee/chiupam'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          white_list: "surge"
          force_update: true

      - name: Delete Workflow Runs # 删除执行日志
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0